### ISSUE TITLE
register.php - En sida med ett formulär

### ISSUE THREAD

**Issue by lyret** [WIEG2017/fettis-exercises#4]
sidan ska innehålla ett registreringsformulär som när man fyller i det och skickar det sparar ens uppgifter i session

Om uppgifterna redan finns i session ska sidan skriva ut vad man tidigare registrerat

**Comment by andremedie** [comment]
Denna haffar jag gärna!

**Comment by andremedie** [comment]
Uppgift slutförd

**Comment by lyret** [comment]
Behövs en  pull request :) Såg allafall bra ut, vi tar det sista imorgon 👍
