### ISSUE TITLE
finditforme.php - en sökmotor

### ISSUE THREAD

**Issue by lyret** [WIEG2017/fettis-exercises#8]
Gör en sida med ett GET formulär där man kan skriva in ett sökord och välja antingen duckduckgo eller google.

När man skickar formuläret ska man skickas vidare till google eller duckduckgo med rätt sökning

*tips*:

Google och DuckDuckGo använder också GET för att göra sökningar
exempel: `https://www.google.se/search?q=mysearch`

**Comment by ThommyDude** [comment]
Jag tar den här eftersom ingen annan säger nåt emot detta.
(Väntar tills jag är inbjuden och skriver mig själv som assignee)
